mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^photo_gallery/', include('photo_gallery.urls', namespace="photo_gallery")),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    # set static handler
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

photo_gallery/urls.py
from django.conf.urls import patterns, url
from photo_gallery import views

urlpatterns= patterns('',
    # ex: /photo_gallery/
    url(r'^$', views.IndexView.as_view(), name='index'),
    #ex: /photo_gallery/5/
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    #ex: /photo_gallery/5/results/
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(),name='results'),
    #ex: /photo_gallery/5/vote/
    url(r'^(?P<item_id>\d+)/vote/$', views.vote, name = 'vote'),
)

photo_gallery/models.py
from django.db import models
from photo_gallery.fields import ThumbnailImageField
import datetime
from django.utils import timezone
from django.core.urlresolvers import reverse

class Item(models.Model):
    name = models.CharField(max_length = 250)
    description = models.TextField()

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('item_detail', args=[str(self.id)])

class Photo(models.Model):
    item = models.ForeignKey(Item)
    title = models.CharField(max_length = 100)
    image = ThumbnailImageField(upload_to='photos')
    caption = models.CharField(max_length = 250, blank = True)
    votes = models.IntegerField(default = 0)
    class Meta:
        ordering = ['title']

    def __unicode__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('photo_detail',  args=[str(self.id)])

photo_gallery/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from photo_gallery.models import Item, Photo

class IndexView(generic.ListView):
    template_name = 'photo_gallery/index.html'
    context_object_name = 'latest_item_list'

    def get_queryset(self):
        return Item.objects.order_by('name')[:5]

class DetailView(generic.DetailView):
    model = Item
    template_name = 'photo_gallery/detail.html'
    
    def get_queryset(self):
        return Item.objects.all()

class ResultsView(generic.DetailView):
    model = Item
    template_name = 'photo_gallery/results.html'

def vote(request, item_id):
    p = get_object_or_404(Item, pk=item_id)
    try:
        selected_photo= p.photo_set.get(pk=request.POST['photo'])
    except (KeyError, Photo.DoesNotExist):
        return render(request, 'photo_gallery/detail.html', {
            'photo':p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_photo.votes +=1
        selected_photo.save()
        return HttpResponseRedirect(reverse('photo_gallery:results', args=(p.id,)))

photo_gallery/templates/photo_gallery/detail.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'photo_gallery/style.css' %}"/>

<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}style.css"/>
<h1>{{ item.name }}</h1>
{% if error_massage %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'photo_gallery:vote' item.id %}" method="post">
{% csrf_token %}
<table>
<tr>
{% for photo in item.photo_set.all %}
    <th>
        <input type="radio" name="photo" id="photo{{ forloop.counter }}" value="{{ photo.id }}" />
        <label for="photo{{ forloop.counter }}">{{ photo.title }}</label><br />
    </th>
{% endfor %}
</tr>
<tr>
{% for photo in item.photo_set.all %}
    <td>
        <img src="{{photo.image.thumb_url}}", id="image">
    </td>
{% endfor %}
</tr>
</table>  
<input type="submit" value="Vote" />
</form>

photo_gallery/templates/photo_gallery/index.html
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}style.css"/>
{% if latest_item_list %}
    <ul>
    {% for item in latest_item_list %}
<li><a href="{% url 'photo_gallery:detail' item.id %}">{{item.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p> No item are available. </p>
{% endif %}

photo_gallery/templates/photo_gallery/item_detail.html
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}style.css"/>
<h1>{{ item.name }}</h1>

photo_gallery/templates/photo_gallery/results.html
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}style.css"/>
<h1>{{ item.name }}</h1>
{% for photo in item.photo_set.all %}
    <div class="images">
    <div>   
        {{ photo.title }}
        <span class="votes">{{ photo.votes }}</span>
        <hr style="width:{{photo.votes}}%;">
    </div></div>
{% endfor %}